// <auto-generated />
using System;
using EmployeeRole.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeRole.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230404063849_removeMtMRelationships")]
    partial class removeMtMRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EmployeeRole.Data.DataModels.EmployeeDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeRole.Data.DataModels.RoleDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid?>("EmployeeDataModelId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeDataModelId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EmployeeRole.Data.DataModels.RoleDataModel", b =>
                {
                    b.HasOne("EmployeeRole.Data.DataModels.EmployeeDataModel", null)
                        .WithMany("Roles")
                        .HasForeignKey("EmployeeDataModelId");
                });

            modelBuilder.Entity("EmployeeRole.Data.DataModels.EmployeeDataModel", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
